---
fixtures:
  symlinks:
    tpm: "#{source_dir}"
    augeasproviders_core: "#{source_dir}/../augeasproviders_core"
    augeasproviders_grub: "#{source_dir}/../augeasproviders_grub"
    common: "#{source_dir}/../common"
    stdlib: "#{source_dir}/../stdlib"
